#ifndef __ITEM_H__
#define __ITEM_H__

class Item {
public:
	enum EItemType {
		EITEMTYPE_MAGENTA_ORB,
		EITEMTYPE_RED_ORB,
		EITEMTYPE_GREEN_ORB,
		EITEMTYPE_BLUE_ORB,
		EITEMTYPE_PURPLE_ORB,

		EITEMTYPE_CAT,

		EITEMTYPE_CYAN_POTION_MEDIUM,
		EITEMTYPE_RED_POTION_MEDIUM,
		EITEMTYPE_CYAN_POTION_SMALL,
		EITEMTYPE_YELLOW_POTION_MEDIUM,

		EITEMTYPE_COINS,
		EITEMTYPE_BOOK,
		EITEMTYPE_FISH,
		EITEMTYPE_GOLDEN_LEAF,
		EITEMTYPE_RUBY,
		EITEMTYPE_KEY,
		EITEMTYPE_COIN,
		EITEMTYPE_LEAF,
		EITEMTYPE_MINERAL,
		EITEMTYPE_SHIELD,
		EITEMTYPE_ORB,
		EITEMTYPE_PACKET,
		EITEMTYPE_COAL,
		EITEMTYPE_WOOD,
		EITEMTYPE_SWORD,
		EITEMTYPE_PAPER,
		EITEMTYPE_APPLE,


		EITEMTYPE_NONE
	};
private:

public:
	Item();
	~Item();
};

#endif  // __ABILITY_H__